# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_hazmat_animated.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_hazmat_animated', 'function_path': 'animated_java:player_hazmat_animated/animations/death.1/next_frame'}
execute if score @s aj.death.1.frame matches 141.. run scoreboard players set @s aj.death.1.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.death.1.frame
execute at @s run function animated_java:player_hazmat_animated/animations/death.1/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.death.1.frame 1