# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:hands_tools_polaroid rig_hash set value '3b5629527c5d66cdcbd28d9eda6d755401aec0c8cabce888619831a981d02a37'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.use.frame dummy