# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:player_hazmat rig_hash set value '81583f425ca67e4b995e090075ceef4d9367842dc555c9c02291abc9975e33e0'
scoreboard objectives add aj.walk_start.frame dummy
scoreboard objectives add aj.idle_loop.frame dummy
scoreboard objectives add aj.walk_loop.frame dummy
scoreboard objectives add aj.walk_stop.frame dummy
scoreboard objectives add aj.walk_stop2.frame dummy
scoreboard objectives add aj.sprint_loop.frame dummy