# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:player_hazmat rig_hash set value 'e272b5c7ceb1f59ebefa1a4a7066a4758bf59e05f4475bf5695f107c9582e4e6'
scoreboard objectives add aj.walk_start.frame dummy
scoreboard objectives add aj.idle_loop.frame dummy
scoreboard objectives add aj.walk_loop.frame dummy
scoreboard objectives add aj.walk_stop.frame dummy
scoreboard objectives add aj.walk_stop2.frame dummy
scoreboard objectives add aj.sprint_loop.frame dummy