# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.walk_start.frame
scoreboard objectives remove aj.idle_loop.frame
scoreboard objectives remove aj.walk_loop.frame
scoreboard objectives remove aj.walk_stop.frame
scoreboard objectives remove aj.walk_stop2.frame
scoreboard objectives remove aj.sprint_loop.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:player_hazmat)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'player_hazmat'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']