# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.death.upright.2.frame
function animated_java:player_hazmat_animated/animations/death.upright.2/zzz/apply_frame with storage aj:temp args
execute if score @s aj.death.upright.2.frame matches 1 run return run function animated_java:player_hazmat_animated/animations/death.upright.2/stop
scoreboard players add @s aj.death.upright.2.frame 1