# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_weapons_broom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hands_weapons_broom', 'function_path': 'animated_java:hands_weapons_broom/variants/slim/apply'}
execute on passengers if entity @s[tag=aj.hands_weapons_broom.bone.broom] run function animated_java:hands_weapons_broom/variants/slim/zzz/apply_to_bone_broom
execute on passengers if entity @s[tag=aj.hands_weapons_broom.bone.right_arm] run function animated_java:hands_weapons_broom/variants/slim/zzz/apply_to_bone_right_arm
execute on passengers if entity @s[tag=aj.hands_weapons_broom.bone.left_arm] run function animated_java:hands_weapons_broom/variants/slim/zzz/apply_to_bone_left_arm
return 1