# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^-0.03125 ^1.6875 ^0.3 {Tags:["aj.global.bone.body.decendant","aj.global.bone.body.decendant.locator","aj.global.bone.body.tree","aj.global.bone.head_const.child","aj.global.bone.head_const.child.locator","aj.global.bone.head_const.decendant","aj.global.bone.head_const.decendant.locator","aj.global.bone.head_const.tree","aj.global.bone.upper.decendant","aj.global.bone.upper.decendant.locator","aj.global.bone.upper.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.camera","aj.new","aj.player_hazmat_animated.bone.body.decendant","aj.player_hazmat_animated.bone.body.decendant.locator","aj.player_hazmat_animated.bone.body.tree","aj.player_hazmat_animated.bone.head_const.child","aj.player_hazmat_animated.bone.head_const.child.locator","aj.player_hazmat_animated.bone.head_const.decendant","aj.player_hazmat_animated.bone.head_const.decendant.locator","aj.player_hazmat_animated.bone.head_const.tree","aj.player_hazmat_animated.bone.upper.decendant","aj.player_hazmat_animated.bone.upper.decendant.locator","aj.player_hazmat_animated.bone.upper.tree","aj.player_hazmat_animated.entity","aj.player_hazmat_animated.locator","aj.player_hazmat_animated.locator.camera","aj.player_hazmat_animated.node","aj.player_hazmat_animated.node.camera"]}
execute as @n[ type=minecraft:item_display, tag=aj.new, tag=aj.player_hazmat_animated.locator.camera, distance=..2.7142440936167755 ] run function animated_java:player_hazmat_animated/zzz/summon/as_data_entity/as_locator/camera
data modify entity @s data.uuids.locator_camera set from storage aj:uuid main.out
data modify entity @s data.locators.camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.right_leg_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.left_leg_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.right_arm_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.left_arm_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.helmet] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_helmet set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.player_hazmat_animated.node.upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upper set from storage aj:uuid main.out