# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:player_hazmat_animated/zzz/summon/as_data_entity
execute if data storage aj:temp args.variant run function animated_java:player_hazmat_animated/zzz/summon/variant_arg/process with storage aj:temp args
function animated_java:player_hazmat_animated/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:player_hazmat_animated/zzz/summon/animation_arg/process with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
ride @n[tag=aj.global.data] mount @n[tag=aj.global.root]
tag @s add player_hazmat_animated.model
tag @s add player_hazmat_animated.new
tag @s remove aj.new
execute on passengers run tag @s remove aj.new