# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:xander rig_hash set value 'd8805ab8e20392ad9892da25769b49eb480bc961035bd299f56862fa0471f73a'
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.idle.frame dummy