# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.i dummy
scoreboard objectives add aj.id dummy
scoreboard objectives add aj.is_rig_loaded dummy
scoreboard objectives add aj.tween_duration dummy
scoreboard players add aj.last_id aj.id 0
function animated_java:global/gu/on_load
function #animated_java:global/on_load
scoreboard players reset * aj.is_rig_loaded
execute as @e[type=item_display,tag=aj.global.root] at @s run function animated_java:global/root/on_load