# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9659f,0.2588f,-0.7969f,0f,0.2588f,-0.9659f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_knife) {transformation: [-0.9962f,0.0872f,0f,-0.668f,0.0872f,0.9962f,0f,-1.9946f,0f,0f,-1f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-0.9962f,0.0872f,0f,-0.375f,0.0872f,0.9962f,0f,-0.7969f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [-0.9962f,-0.0872f,0f,0.375f,-0.0872f,0.9962f,0f,-0.7969f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-1.875f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg) {transformation: [-0.999f,0.0436f,0f,-0.2344f,0.0436f,0.999f,0f,-1.9219f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg) {transformation: [-0.999f,-0.0436f,0f,0.2344f,-0.0436f,0.999f,0f,-1.9687f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_leg_hazmat) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_leg_hazmat) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm_hazmat) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm_hazmat) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_helmet) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [0f,0f,0f,0f,0f,0f,0f,-1.625f,0f,0f,0f,-0.7187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{},"locators":{"left_arm_grab":{"posx":0.704623987749921,"posy":-2.1263303555215156,"posz":8.629155112003845e-17,"roty":0,"rotx":0},"camera":{"posx":-3.124999999119789e-7,"posy":-1.6249974999999999,"posz":-0.718747,"roty":0,"rotx":0}}}