# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.the_butcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_butcher', 'function_path': 'animated_java:the_butcher/animations/pause_all'}
tag @s remove aj.the_butcher.animation.idle.playing
tag @s remove aj.the_butcher.animation.idle2.playing
tag @s remove aj.the_butcher.animation.walk.playing
tag @s remove aj.the_butcher.animation.pick.up.playing
tag @s remove aj.the_butcher.animation.drag.walk2.playing
tag @s remove aj.the_butcher.animation.drag.walk.playing