# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.light] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_light set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.inner] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_inner set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.outer] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_outer set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.inner1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_inner1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.outer1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_outer1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.right_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right_arm set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.hands_tools_flashlight.node.left_arm] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left_arm set from storage animated_java:gu out