# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add hands_weapons.model
tag @s add new
function animated_java:hands_tools_flashlight/animations/equip/play