# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:player_hazmat_head/animations/walk_loop/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.walk_loop.frame 1