# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:player_hazmat_head rig_hash set value 'fa4ceca8d315a7d8ba7b0416cacfd543620dbc3d733d1181ec6f2744f06795c0'
scoreboard objectives add aj.walk_start.frame dummy
scoreboard objectives add aj.idle_loop.frame dummy
scoreboard objectives add aj.walk_loop.frame dummy
scoreboard objectives add aj.walk_stop.frame dummy
scoreboard objectives add aj.walk_stop2.frame dummy
scoreboard objectives add aj.sprint_loop.frame dummy