# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add nightshifts.tools.spirit_box.cooldown
playsound nightshifts:sfx.tools.spirit_box.white_noise master @p ~ ~ ~ 0.4 1