# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add nightshifts.tools.spirit_box.cooldown
stopsound @p * nightshifts:sfx.tools.spirit_box.white_noise
execute on passengers as @s[tag=aj.hands_tools_spiritbox.bone.screen] run data modify entity @s brightness set value {sky:0,block:0}