# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add weapon.hit.cooldown
playsound nightshifts:sfx.tools.flashlight.click master @p ~ ~ ~ 0.3 1 0.3