# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_hazmat_animated.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_hazmat_animated', 'function_path': 'animated_java:player_hazmat_animated/animations/death.mutilated.3/stop'}
tag @s remove aj.player_hazmat_animated.animation.death.mutilated.3.playing
scoreboard players set @s aj.death.mutilated.3.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:player_hazmat_animated/animations/death.mutilated.3/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only