# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^-0.03125 ^-1.375 ^-0.41875 {Tags:["aj.global.bone.head_const.child","aj.global.bone.head_const.child.locator","aj.global.bone.head_const.decendant","aj.global.bone.head_const.decendant.locator","aj.global.bone.head_const.tree","aj.global.bone.player.decendant","aj.global.bone.player.decendant.locator","aj.global.bone.player.tree","aj.global.bone.upper.decendant","aj.global.bone.upper.decendant.locator","aj.global.bone.upper.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.camera","aj.new","aj.the_butcher.bone.head_const.child","aj.the_butcher.bone.head_const.child.locator","aj.the_butcher.bone.head_const.decendant","aj.the_butcher.bone.head_const.decendant.locator","aj.the_butcher.bone.head_const.tree","aj.the_butcher.bone.player.decendant","aj.the_butcher.bone.player.decendant.locator","aj.the_butcher.bone.player.tree","aj.the_butcher.bone.upper.decendant","aj.the_butcher.bone.upper.decendant.locator","aj.the_butcher.bone.upper.tree","aj.the_butcher.entity","aj.the_butcher.locator","aj.the_butcher.locator.camera","aj.the_butcher.node","aj.the_butcher.node.camera"]}
execute as @n[ type=minecraft:item_display, tag=aj.new, tag=aj.the_butcher.locator.camera, distance=..4.065711067908273 ] run function animated_java:the_butcher/zzz/summon/as_data_entity/as_locator/camera
data modify entity @s data.uuids.locator_camera set from storage aj:uuid main.out
data modify entity @s data.locators.camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.knife] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_knife set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.torso] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_torso set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.right_leg_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_leg_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.left_leg_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_leg_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.right_arm_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right_arm_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.left_arm_hazmat] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left_arm_hazmat set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.helmet] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_helmet set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.the_butcher.node.upper] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_upper set from storage aj:uuid main.out