# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_weapons_fireextinguisher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hands_weapons_fireextinguisher', 'function_path': 'animated_java:hands_weapons_fireextinguisher/animations/hit/next_frame'}
execute if score @s aj.hit.frame matches 21.. run scoreboard players set @s aj.hit.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.hit.frame
execute at @s run function animated_java:hands_weapons_fireextinguisher/animations/hit/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.hit.frame 1