# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_weapons_fireextinguisher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hands_weapons_fireextinguisher', 'function_path': 'animated_java:hands_weapons_fireextinguisher/animations/hit/stop'}
tag @s remove aj.hands_weapons_fireextinguisher.animation.hit.playing
scoreboard players set @s aj.hit.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:hands_weapons_fireextinguisher/animations/hit/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only