# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p remove weapon.hit.cooldown
tag @p add nightshifts.tools.spirit_box.cooldown
scoreboard players set @p tools.spirit_box.light 0
execute on passengers as @s[tag=aj.hands_tools_spiritbox.bone.screen] run data modify entity @s brightness set value {sky:0,block:0}