# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players set @p tools.spirit_box.light 15
function animated_java:hands_tools_spiritbox/animations/ambient/play