# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add weapon.hit.cooldown
playsound nightshifts:sfx.tools.polaroid.click master @a ~ ~ ~ 1 1
execute as @p at @s anchored eyes positioned ^ ^ ^1 if block ~ ~ ~ #air align xyz positioned ~0.5 ~0.5 ~0.5 run return run function weapons:polaroid/light/init
execute as @p at @s anchored eyes positioned ^ ^ ^ if block ~ ~ ~ #air align xyz positioned ~0.5 ~0.5 ~0.5 run return run function weapons:polaroid/light/init