# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_hazmat_animated.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_hazmat_animated', 'function_path': 'animated_java:player_hazmat_animated/at_all_locators'}
data remove storage aj:temp args
$data modify storage aj:temp args.command set value '$(command)'
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:player_hazmat_animated/zzz/at_all_locators/as_data