# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.death.1.frame
scoreboard objectives remove aj.death.2.frame
scoreboard objectives remove aj.death.3.frame
scoreboard objectives remove aj.death.mutilated.1.frame
scoreboard objectives remove aj.death.mutilated.2.frame
scoreboard objectives remove aj.death.mutilated.3.frame
scoreboard objectives remove aj.death.upright.1.frame
scoreboard objectives remove aj.death.upright.2.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"player_hazmat_animated",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]