# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_hazmat_animated.root] run return 0
execute on passengers if entity @s[tag=aj.player_hazmat_animated.data] unless data entity @s {data:{rigHash: '78cb3edc8c7387368dab3be02966919e87ddbc2fe13da32ac5813999b786ba50'}} on vehicle run function animated_java:player_hazmat_animated/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1