# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_hazmat_animated.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.1.playing] run function animated_java:player_hazmat_animated/animations/death.1/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.2.playing] run function animated_java:player_hazmat_animated/animations/death.2/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.3.playing] run function animated_java:player_hazmat_animated/animations/death.3/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.mutilated.1.playing] run function animated_java:player_hazmat_animated/animations/death.mutilated.1/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.mutilated.2.playing] run function animated_java:player_hazmat_animated/animations/death.mutilated.2/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.mutilated.3.playing] run function animated_java:player_hazmat_animated/animations/death.mutilated.3/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.upright.1.playing] run function animated_java:player_hazmat_animated/animations/death.upright.1/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat_animated.animation.death.upright.2.playing] run function animated_java:player_hazmat_animated/animations/death.upright.2/zzz/on_tick
execute on passengers if entity @s[tag=aj.player_hazmat_animated.data] run function animated_java:player_hazmat_animated/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~