# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_weapons_fireextinguisher.root] run return 0
execute on passengers if entity @s[tag=aj.hands_weapons_fireextinguisher.data] unless data entity @s {data:{rigHash: '29e3bf910e5397296be9a55ed44efff87816ef3dd5d9aa0e3c721ffc511148f6'}} on vehicle run function animated_java:hands_weapons_fireextinguisher/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1