# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_weapons_broom.root] run return 0
execute on passengers if entity @s[tag=aj.hands_weapons_broom.data] unless data entity @s {data:{rigHash: 'd2048c07bf760816792ae6913d41b26ed68801d459a474ec032f34bbb89af3cc'}} on vehicle run function animated_java:hands_weapons_broom/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1