# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_weapons_broom.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.hands_weapons_broom.animation.equip.playing] run function animated_java:hands_weapons_broom/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.hands_weapons_broom.animation.hit.playing] run function animated_java:hands_weapons_broom/animations/hit/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~