# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.new
function animated_java:global/internal/gu/convert_uuid_array_to_string
tp @s ^-0.03125 ^1.6875 ^0.3 ~0 ~0
tag @s add player_hazmat_animated.camera
data modify entity @s teleport_duration set value 2
data modify entity @s interpolation_duration set value 2