# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value 'e272b5c7ceb1f59ebefa1a4a7066a4758bf59e05f4475bf5695f107c9582e4e6'