# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:temp args.export_namespace set from entity @s data.export_namespace
data modify entity @s data.rig_hash set value '467d0c0e589ac800bfa5b4665f9dea803a1c5775d43adac338c5b152c79ac6df'