# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:hands_tools_radio/animations/ambience/zzz/apply_frame {frame: 136}
scoreboard players add @s aj.ambience.frame 1