# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
execute if score @s aj.ambience.frame matches -1 run function animated_java:hands_tools_radio/animations/ambience/zzz/function_keyframe_loop_patch
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.ambience.frame
function animated_java:hands_tools_radio/animations/ambience/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.ambience.frame matches 135.. run return run scoreboard players set @s aj.ambience.frame -1
scoreboard players add @s aj.ambience.frame 1