# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:hands_weapons_broom/zzz/summon/as_data_entity
execute if data storage aj:temp args.variant run function animated_java:hands_weapons_broom/zzz/summon/variant_arg/process with storage aj:temp args
function animated_java:hands_weapons_broom/set_default_pose
execute if data storage aj:temp args.animation run function animated_java:hands_weapons_broom/zzz/summon/animation_arg/process with storage aj:temp args
tp @s ~ ~ ~ ~ ~
execute at @s on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s add hands_weapons.model
tag @s add new
execute as @e[tag=aj.hands_weapons_broom.root,distance=..1] run data modify entity @s view_range set value 0.005
function animated_java:hands_weapons_broom/animations/equip/play
tag @s remove aj.new
execute on passengers run tag @s remove aj.new