# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.the_butcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_butcher', 'function_path': 'animated_java:the_butcher/animations/walk/apply_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.walk.frame $(frame)
execute at @s run function animated_java:the_butcher/animations/walk/zzz/apply_frame with storage aj:temp args