# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:hands_tools_flashlight rig_hash set value 'fc3f17d7482154472d3d33b1714d227168a0c791c9cf5ad96d4f45b74f84572a'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.use.frame dummy
scoreboard objectives add aj.use_offhand.frame dummy