# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:hands_tools_spiritbox rig_hash set value '90885352cbc1293a92b28517ff37a1b138dedbad5c44fdfac752415f0bf756b9'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.ambient.frame dummy
scoreboard objectives add aj.off.frame dummy