# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:hands_tools_spiritbox rig_hash set value 'ff6092c3ab358f7e567072ab5759da3aa9dea65144446c18ee55cb29bd0e1c5b'
scoreboard objectives add aj.equip.frame dummy
scoreboard objectives add aj.ambient.frame dummy