# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_tools_radio.root] run return 0
execute if entity @s[tag=aj.hands_tools_radio.animation.equip.playing] run function animated_java:hands_tools_radio/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.hands_tools_radio.animation.use.playing] run function animated_java:hands_tools_radio/animations/use/zzz/on_tick
execute if entity @s[tag=aj.hands_tools_radio.animation.ambience.playing] run function animated_java:hands_tools_radio/animations/ambience/zzz/on_tick
execute on passengers run rotate @s ~ ~