# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_butcher/animations/drag.walk2/zzz/apply_frame {frame: 20}
scoreboard players add @s aj.drag.walk2.frame 1