# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:player_hazmat_head/animations/sprint_loop/zzz/apply_frame {frame: 13}
scoreboard players add @s aj.sprint_loop.frame 1