# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.the_butcher.root] run return 0
execute on passengers if entity @s[tag=aj.the_butcher.data] unless data entity @s {data:{rigHash: '27d0d51ee99f986aca52c4d780cffd2426dca75475208d8c62c0bc217b65b764'}} on vehicle run function animated_java:the_butcher/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1