# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.the_butcher.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.the_butcher.animation.idle.playing] run function animated_java:the_butcher/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.the_butcher.animation.idle2.playing] run function animated_java:the_butcher/animations/idle2/zzz/on_tick
execute if entity @s[tag=aj.the_butcher.animation.walk.playing] run function animated_java:the_butcher/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.the_butcher.animation.pick.up.playing] run function animated_java:the_butcher/animations/pick.up/zzz/on_tick
execute if entity @s[tag=aj.the_butcher.animation.drag.walk2.playing] run function animated_java:the_butcher/animations/drag.walk2/zzz/on_tick
execute if entity @s[tag=aj.the_butcher.animation.drag.walk.playing] run function animated_java:the_butcher/animations/drag.walk/zzz/on_tick
execute on passengers if entity @s[tag=aj.the_butcher.data] run function animated_java:the_butcher/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~