# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @p add weapon.hit.cooldown
execute on vehicle run stopsound @s * nightshifts:sfx.tools.radio.idle
playsound nightshifts:sfx.tools.radio.use master @p ~ ~ ~ 1 1