# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s add player_hazmat.new
tag @s add player_hazmat.model
function animated_java:player_hazmat/animations/idle.loop/play