# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.the_butcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_butcher', 'function_path': 'animated_java:the_butcher/as_locator'}
data remove storage aj:temp args
$data modify storage aj:temp args merge value {name:'$(name)', command:'$(command)'}
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:the_butcher/zzz/as_locator/as_data {name: $(name)}