# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_weapons_broom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hands_weapons_broom', 'function_path': 'animated_java:hands_weapons_broom/animations/equip/next_frame'}
execute if score @s aj.equip.frame matches 31.. run scoreboard players set @s aj.equip.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.equip.frame
execute at @s run function animated_java:hands_weapons_broom/animations/equip/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.equip.frame 1