# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_weapons_broom.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'hands_weapons_broom', 'function_path': 'animated_java:hands_weapons_broom/animations/equip/tween'}
function animated_java:hands_weapons_broom/animations/pause_all
tag @s add aj.hands_weapons_broom.animation.equip.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.equip.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function animated_java:hands_weapons_broom/animations/equip/zzz/apply_frame {frame: 0}
$execute at @s run function animated_java:hands_weapons_broom/animations/equip/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i