# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute on passengers if entity @s[tag=aj.global.data] run function animated_java:hands_weapons_broom/animations/hit/zzz/frames/$(frame) with entity @s data.uuids
return 1