# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_light) {transformation: [-1f,0f,0f,-0.5937f,0f,-1f,0f,-2.1628f,0f,0f,1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_inner) {transformation: [-1f,0f,0f,-0.5937f,0f,-1f,0f,-2.1628f,0f,0f,1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_outer) {transformation: [-1f,0f,0f,-0.5937f,0f,-1f,0f,-2.1628f,0f,0f,1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_inner1) {transformation: [-1f,0f,0f,-0.5937f,0f,-1f,0f,-2.1628f,0f,0f,1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_outer1) {transformation: [-1f,0f,0f,-0.5937f,0f,-1f,0f,-2.1628f,0f,0f,1f,0.5f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right_arm) {transformation: [-1f,0f,0f,-0.4688f,0f,1f,0f,-1.3437f,0f,0f,-1f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left_arm) {transformation: [0f,0f,0f,0.5313f,0f,0f,0f,-1.5937f,0f,0f,0f,0.5625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:hands_tools_flashlight/animations/equip/zzz/frames/0_root_function