# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp args merge from entity @s data.locators.camera
function animated_java:player_hazmat_animated/zzz/at_all_locators/execute_at_transform with storage aj:temp args