# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_tools_flashlight.root] run return 0
execute if entity @s[tag=aj.hands_tools_flashlight.animation.equip.playing] run function animated_java:hands_tools_flashlight/animations/equip/zzz/on_tick
execute if entity @s[tag=aj.hands_tools_flashlight.animation.use.playing] run function animated_java:hands_tools_flashlight/animations/use/zzz/on_tick
execute if entity @s[tag=aj.hands_tools_flashlight.animation.use_offhand.playing] run function animated_java:hands_tools_flashlight/animations/use_offhand/zzz/on_tick
execute on passengers run rotate @s ~ ~