# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.the_butcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_butcher', 'function_path': 'animated_java:the_butcher/animations/drag.walk2/next_frame'}
execute if score @s aj.drag.walk2.frame matches 21.. run scoreboard players set @s aj.drag.walk2.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.drag.walk2.frame
execute at @s run function animated_java:the_butcher/animations/drag.walk2/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.drag.walk2.frame 1