# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:the_butcher/root/zzz/on_tick/select_locator_left_arm_grab with entity @s data.locators.left_arm_grab
function animated_java:the_butcher/root/zzz/on_tick/select_locator_camera with entity @s data.locators.camera