# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.hands_tools_polaroid.root] run return 0
execute on passengers if entity @s[tag=aj.hands_tools_polaroid.data] unless data entity @s {data:{rigHash: 'dcbd94eee78e3cb5faa61d628fdf6a7514e8029f6889b7c8c2755de70de9a3d2'}} on vehicle run function animated_java:hands_tools_polaroid/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1