# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if function animated_java:global/util/is_rig_outdated run function animated_java:global/root/outdated_warning/modify_rig
scoreboard players set @s aj.is_rig_loaded 1