# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_player_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0938f,0f,0f,-1f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.4062f,0f,0f,-1f,-0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute on vehicle unless entity @s[tag=aj.transforms_only] at @s run function animated_java:player_hazmat_head/animations/walk_stop/zzz/frames/5_root_function