# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.player_hazmat_animated.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'player_hazmat_animated', 'function_path': 'animated_java:player_hazmat_animated/variants/slim/apply'}
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.right_leg_hazmat] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_right_leg_hazmat
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.left_leg_hazmat] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_left_leg_hazmat
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.right_arm_hazmat] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_right_arm_hazmat
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.left_arm_hazmat] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_left_arm_hazmat
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.helmet] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_helmet
execute on passengers if entity @s[tag=aj.player_hazmat_animated.bone.upper] run function animated_java:player_hazmat_animated/variants/slim/zzz/apply_to_bone_upper
return 1