# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.the_butcher.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'the_butcher', 'function_path': 'animated_java:the_butcher/animations/idle2/stop'}
tag @s remove aj.the_butcher.animation.idle2.playing
scoreboard players set @s aj.idle2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:the_butcher/animations/idle2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only