# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.hands_tools_flashlight.root] run return run tellraw @a [{color:'red',text:''},{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:hands_tools_flashlight)'},'\n → ᴇʀʀᴏʀ: ',{color:'red',underlined:true,text:'Function Not Executed as Root Entity'},'\n\n ',{color:'yellow',text:'[This Function]',hover_event:{action:show_text,value:[{color:'yellow',text:'animated_java:hands_tools_flashlight/animations/use/tween'}]}}," must be executed as the rig's root entity.",{color:'white',text:'\n\n ≡ '},{color:'aqua',underlined:true,text:'ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ',click_event:{action:suggest_command,command:'/execute as @e[tag=aj.hands_tools_flashlight.root] run function animated_java:hands_tools_flashlight/animations/use/tween'}},'\n\n ',{color:'blue',italic:true,underlined:true,text:'▶ Learn More ◀',click_event:{action:open_url,url:'https://animated-java.dev/docs/rigs/controlling-a-rig-instance'}},'\n']
function animated_java:hands_tools_flashlight/animations/pause_all
tag @s add aj.hands_tools_flashlight.animation.use.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.use.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function animated_java:hands_tools_flashlight/animations/use/zzz/apply_frame {frame: 0}
$execute at @s run function animated_java:hands_tools_flashlight/animations/use/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i