# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.player_hazmat.root] run return 0
execute if entity @s[tag=aj.player_hazmat.animation.walk_start.playing] run function animated_java:player_hazmat/animations/walk_start/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat.animation.idle_loop.playing] run function animated_java:player_hazmat/animations/idle_loop/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat.animation.walk_loop.playing] run function animated_java:player_hazmat/animations/walk_loop/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat.animation.walk_stop.playing] run function animated_java:player_hazmat/animations/walk_stop/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat.animation.walk_stop2.playing] run function animated_java:player_hazmat/animations/walk_stop2/zzz/on_tick
execute if entity @s[tag=aj.player_hazmat.animation.sprint_loop.playing] run function animated_java:player_hazmat/animations/sprint_loop/zzz/on_tick
execute on passengers run rotate @s ~ ~